---
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    brief:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%H:%M:%S'
    precice:
      format: '%(asctime)s - %(threadName)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      level: INFO
      class: logging.StreamHandler
      formatter: brief
      stream: ext://sys.stdout
    file:
      level: DEBUG
      class: logging.handlers.RotatingFileHandler
      formatter: precice
      filename: debug.log
      mode: a
      maxBytes: 2560000
      backupCount: 1
  root:
    level: DEBUG
    handlers:
    - console
    - file
  loggers:
    mt5-correlation:
      level: DEBUG
      handlers:
      - console
      - file
      propagate: 0
charts:
  colormap: Dark2
developer:
  inspection: true
window:
  x: 357
  y: 222
  width: 1051
  height: 446
  style: 541072960
settings_window:
  x: 374
  y: 380
  width: 624
  height: 312
...